import { MigrationInterface, QueryRunner, getRepository } from "typeorm";
import { Bank } from "../entity/Bank";

export class AddBanks1583907391420 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<any> {
    const BankList = [
      "1st Valley Bank (a development bank)",
      "AllBank, Inc.",
      "Bank of Makati",
      "Bank One Savings and Trust Corporation",
      "Bataan Development Bank",
      "Bataan Savings and Loan Bank",
      "BPI Direct BanKo, Inc. (a subsidiary of BPI)",
      "BPI Family Savings Bank (a subsidiary of BPI)",
      "Business and Consumers Bank",
      "CARD SME Bank, Inc. (a thrift bank)",
      "Century Savings Bank Corporation",
      "China Bank Savings (a subsidiary of Chinabank)",
      "CitySavings Bank (a subsidiary of Unionbank)",
      "Citystate Savings Bank",
      "Cordillera Savings Bank, Inc.",
      "Dumaguete City Development Bank, Inc.",
      "Enterprise Bank, Inc.",
      "Equicom Savings Bank (Equicom)",
      "Farmers Savings and Loan Bank, Inc.",
      "First Consolidated Bank, Inc.",
      "Hiyas Banking Corporation",
      "HSBC Savings Bank Philippines Inc.",
      "Inter-Asia Development Bank",
      "Isla Bank (a thrift bank)",
      "Legazpi Savings Bank",
      "Lemery Savings and Loan Bank, Inc.",
      "Life Savings Bank, Inc.",
      "Luzon Development Bank",
      "Malasiqui Progressive SLB, Inc.",
      "Malayan Savings Bank",
      "Maritime Savings Bank Corporation",
      "Maximum Savings Bank, Inc.",
      "Merchants Savings and Loan Association, Inc.",
      "Metro Cebu Public Savings Bank",
      "NorthPoint Development Bank, Inc.",
      "Overseas Filipino Bank (acquired by Landbank; government bank)",
      "Pacific Ace Savings Bank, Inc.",
      "Pampanga Development Bank",
      "Pen Bank, Inc. (formerly Peninsula RB, Inc.)",
      "Philippine Business Bank",
      "Philippine Resources Savings Banking Corporation (PR Savings Bank; acquired by CitySavings Bank)",
      "Philippine Savings Bank (PS Bank; a subsidiary of Metrobank)",
      "Philippine Star Development Bank, Inc.",
      "PNB Savings Bank (a subsidiary of PNB)",
      "Producers Savings Bank Corporation (Producers Bank)",
      "Quezon Coconut Bank, Inc. (a thrift bank)",
      "Queen City Development Bank",
      "RCBC Savings Bank (a subsidiary of RCBC)",
      "Sterling Bank of Asia",
      "Sun Savings Bank, Inc.",
      "UCPB Savings Bank (a subsidiary of UCPB)",
      "University Savings Bank",
      "Village Bank, Inc.",
      "Wealth Development Bank Corporation",
      "Yuanta Savings Bank Philippines, Inc.",
      "Agribusiness Rural Bank, Inc.",
      "Aliaga Farmers Rural Bank, Inc.",
      "ASPAC Rural Bank, Inc.",
      "Balanga Rural Bank, Inc.",
      "Banco Dipolog (a rural bank; subsidiary of the Philippine Bank of Communications)",
      "Banco Laguna, Inc. (a rural bank since 1965)",
      "Banco Mabuhay (a rural bank)",
      "Bankways, Inc. (a rural bank)",
      "BDO Network Bank (a subsidiary of BDO Unibank, Inc.)",
      "BHF Rural Bank, Inc.",
      "BOF, Inc. (a rural bank)",
      "Camalig Bank, Inc. (a rural bank)",
      "Cantilan Bank, Inc. (a rural bank)",
      "CARD Bank, Inc. (a MF RB)",
      "Cavite United Rural Bank Corporation (A subsidiary of Asia United Bank Corporation)",
      "Cebuana Lhuillier Rural Bank, Inc.",
      "Common Wealth Rural Bank, Inc.",
      "Community Rural Bank of Catmon (Cebu) Inc.",
      "Community Rural Bank of Dapitan City, Inc.",
      "Cooperative Bank of Bohol",
      "Cooperative Bank of Cotabato",
      "Cooperative Bank of Ilocos Norte",
      "Cooperative Bank of Nueva Vizcaya",
      "Cooperative Bank of Quezon Province",
      "Consolidated Cooperative Bank",
      "Country Builders Bank, Inc. (a rural bank)",
      "D' Asian Hills Bank, Inc. (a rural bank)",
      "Dumaguete Rural Bank Inc. (DRBI)",
      "EastWest Rural Bank, Inc. (a subsidiary of EastWest Bank)",
      "Entrepreneur Rural Bank, Inc.",
      "First Agro-Industrial Rural Bank, Inc. / FAIRBANK Inc.",
      "First Isabela Cooperative Bank (FICO Bank)",
      "First Tagum Rural Bank, Inc.",
      "GM Bank of Luzon, Inc. (a rural bank)",
      "Guagua Rural Bank, Inc.",
      "Highland Rural Bank, Inc.",
      "Ilocos Sur Cooperative Bank",
      "Imus Rural Bank, Inc.",
      "Innovative Bank, Inc. (a rural bank)",
      "Insular Savers Bank, Inc. (a rural bank)",
      "Katipunan Bank, Inc. (a rural bank)",
      "Laguna Prestige Banking Corporation (a rural bank)",
      "Liberty Bank (a rural bank)",
      "LifeBank (a rural bank)",
      "Mactan Rural Bank (Lapu-Lapu City) Inc.",
      "Malarayat Rural Bank, Inc.",
      "Mallig Plains Rural Bank (ISA) Inc.",
      "Marayo Bank, Inc. (a rural bank)",
      "Metro South Cooperative Bank",
      "Mount Makiling Rural Bank, Inc.",
      "MVSM Bank (a rural bank since 1953) Inc.",
      "Network Consolidated Cooperative Bank",
      "New Rural Bank of San Leonardo (N.E.) Inc.",
      "Opportunity Kauswagan Inc. (a microfinance rural bank)",
      "People’s Rural Bank (Gen. Santos City) Inc.",
      "PlanBank (Rural Bank of Canlubang Planters, Inc.)",
      "Quezon Capital Rural Bank, Inc.",
      "Rang-ay Bank, Inc. (a rural bank)",
      "RBG Imperial Bank, Inc. (a rural bank)",
      "RBT Bank, Inc. (a rural bank)",
      "Rizal Bank (a MF RB)",
      "Rural Bank of Angeles, Inc. (A subsidiary of Asia United Bank Corporation)",
      "Rural Bank of Bagabag (N.V.) Inc.",
      "Rural Bank of Bambang (Nueva Vizcaya) Inc.",
      "Rural Bank of Barili (Cebu) Inc.",
      "Rural Bank of Bayombong, Inc.",
      "Rural Bank of Cardona (Rizal) Inc.",
      "Rural Bank of Cauayan, Inc.",
      "Rural Bank of Central Pangasinan (Bayambang) Inc.",
      "Rural Bank of Digos, Inc.",
      "Rural Bank of Dolores (Quezon) Inc.",
      "Rural Bank of Dumangas, Inc.",
      "Rural Bank of Gattaran (Cagayan) Inc.",
      "Rural Bank of General Trias, Inc.",
      "Rural Bank of Guinobatan, Inc.",
      "Rural Bank of Itogon (Benguet) Inc.",
      "Rural Bank of Jaen, Inc.",
      "Rural Bank of Lebak (Sultan Kudarat) Inc.",
      "Rural Bank of Mabalacat, Inc.",
      "Rural Bank of Magdalena (Laguna) Inc.",
      "Rural Bank of Mangaldan",
      "Rural Bank of Maragondon, Inc.",
      "Rural Bank of Maria Aurora (Aurora) Inc.",
      "Rural Bank of Montalban, Inc.",
      "Rural Bank of Pandi (Bulacan) Inc.",
      "Rural Bank of Paracale (Camarines Norte) Inc.",
      "Rural Bank of Pilar (Bataan) Inc.",
      "Rural Bank of Pola (Oriental Mindoro)",
      "Rural Bank of Rizal (Zamboanga del Norte) Inc.",
      "Rural Bank of Rosario (La Union) Inc.",
      "Rural Bank of San Antonio, Inc.",
      "Rural Bank of San Mateo (Isabela) Inc.",
      "Rural Bank of San Pascual (Obando, Bulacan) Inc.",
      "Rural Bank of Solano (Nueva Vizcaya) Inc.",
      "Rural Bank of Sta. Ignacia, Inc.",
      "Rural Bank of Tangub City (Misamis Occidental) Inc.",
      "Rural Bank of Taal, Inc",
      "Saviour Rural Bank, Inc.",
      "Sta. Maria Rural Bank, Inc.",
      "Sugbuanon Rural Bank, Inc.",
      "Summit Bank (rural bank of Tublay, Inc.)",
      "Valiant Bank, Inc. (a rural bank)",
      "Rural Bank of Cuenca Inc."
    ];
    let tempBank = [];
    BankList.forEach(async element => {
      const bank = new Bank();
      bank.bank_name = element;
      tempBank.push(bank);
    });

    await getRepository(Bank).save(tempBank);
    try {
    } catch (e) {
      console.log(e);
    }
  }

  public async down(queryRunner: QueryRunner): Promise<any> {}
}
